#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-weld-api
Version  : 1.1.final
Release  : 1
URL      : https://github.com/weld/api/archive/1.1.Final.tar.gz
Source0  : https://github.com/weld/api/archive/1.1.Final.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jboss/weld/weld-api-bom/1.0/weld-api-bom-1.0.pom
Source2  : https://repo1.maven.org/maven2/org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-weld-api-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-weld-api package.
Group: Data

%description data
data components for the mvn-weld-api package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/weld/weld-api-bom/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jboss/weld/weld-api-bom/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/weld/weld-api-parent/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jboss/weld/weld-api-parent/1.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jboss/weld/weld-api-bom/1.0/weld-api-bom-1.0.pom
/usr/share/java/.m2/repository/org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom
